### ISSUE TITLE
12.0-08 needs some cleanup

### ISSUE THREAD

**Issue by Julien00859** [odoo/technical-training#10]
The debugger is activated and the print statement from python 2 is used

https://github.com/odoo/technical-training/blob/ff58ee4410e94f9f91f10c510ff9222db222a1c4/openacademy/models/course.py#L200
https://github.com/odoo/technical-training/blob/ff58ee4410e94f9f91f10c510ff9222db222a1c4/openacademy/models/course.py#L201

**Comment by sts-odoo** [comment]
done
