### ISSUE TITLE
Missing ir.model.access for v12

### ISSUE THREAD

**Issue by nim-odoo** [odoo/technical-training#15]
Hello guys,

In v12, a model needs `ir.model.access`, otherwise corresponding menus are not displayed. We spent 45 minutes like idiots trying to understand why nothing appeared while the menus were defined ^^.

**Comment by Yenthe666** [comment]
Atleast I haven't been the only one bitten by this in V12 now. 😉

**Comment by Feyensv** [comment]
@jev-odoo has begun a correction of the different parts of the training (also adding security rules).  If he isn't stolen by a R&D Team too soon, he may achieve this for the most important trainings in the following days/weeks :) .
